---
- include_role:
    name: java

- name: Create Ubooquity Directory
  file:
      path: '{{ ansible_env.HOME }}/ubooquity/'
      state: directory

- name: Download "latest" Ubooquity zip
  get_url:
      url: http://vaemendis.net/ubooquity/service/download.php
      dest: '{{ ansible_env.HOME }}/ubooquity/.'
      mode: 01777
#TODO: unzip?

- name: Copy provided start|stop|status script from Ubooquity
  copy:
      src: ubooquity.sh
      dest: '{{ ansible_env.HOME }}/ubooquity/ubooquity.sh'

- name: Copy provided readLogs script from Ubooquity
  copy:
      src: readLogs.sh
      dest: '{{ ansible_env.HOME }}/ubooquity/readLogs.sh'
